// Application constants
export const PAGINATION = {
    DEFAULT_LIMIT: 12,
    MAX_LIMIT: 100,
    DEFAULT_PAGE: 1
};

export const RATE_LIMIT = {
    WINDOW_MS: 15 * 60 * 1000, // 15 minutes
    MAX_REQUESTS: 300
};

export const JWT = {
    DEFAULT_EXPIRES_IN: "10h",
    REMEMBER_ME_EXPIRES_IN: "30d"
};

export const USER_ROLES = {
    ADMIN: "ADMIN",
    EMPLOYEE: "EMPLOYEE"
};

export const USER_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
};

export const TICKET_STATUS = {
    WAITING: "WAITING",
    SERVING: "SERVING",
    COMPLETED: "COMPLETED",
    SKIPPED: "SKIPPED",
    CANCELLED: "CANCELLED"
};

export const ERROR_CODES = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    CONFLICT: "CONFLICT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

    // User
    USER_NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_PASSWORD: "INVALID_PASSWORD",

    // Upload
    FILE_REQUIRED: "FILE_REQUIRED",
    INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
    FILE_TOO_LARGE: "FILE_TOO_LARGE"
};

export const API_RESPONSE = {
    SUCCESS: "success",
    ERROR: "error"
};